# These are supported funding model platforms

github: BuxOrg
custom: https://getbux.io/?utm_source=github&utm_medium=sponsor-link&utm_campaign=bux-console&utm_term=bux-console&utm_content=bux-console
